apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: 3-tier-app-eks
type: Opaque
data:
  DB_USERNAME: mohit  
  DB_PASSWORD: password 
  SECRET_KEY : b2Q8JJOg5M6AYuAnNjprnMPacSIkWkCSVNdhX0/2F6A=
  DATABASE_URL: terraform-2026081121365401270000000d.c9oqic40kui5.us-east-2.rds.amazonaws.com
