apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: 3-tier-app-eks
  labels:
    service: database
spec:
  type: ExternalName
  externalName: terraform-2026082611453048350000000c.c9oqic40kui5.us-east-2.rds.amazonaws.com
